# These are supported funding model platforms

github: [ hackerprod ]
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=YFZZER8VNXKRC' 
© 2022 GitHub, Inc.
Terms
Privacy
Security
Status
